name: Iwanna Films Ltda.
favicon: null
layout_spectrum: 0
typography_spectrum: 0.7457967402879149
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#494949'
    - '#b31c45'
    - '#cccccc'
    - '#969696'
  brandStrength: 0
  lightness: 1
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
